remotePath: /var/www/myapp
ignoreFile: .scpignore
verbose: false
inventoryFile: inventory.ini
inventoryGroup: webservers
steps:
- name: Build app
  type: local
  command: ls

- name: Restart app
  type: ssh
  command: pm2 restart myapp
